development:
    :enginebot_host: "localhost"
    :enginebot_port: 9104
test:
    :enginebot_host: "192.168.1.85"
    :enginebot_port: 9104
production:
    :enginebot_host: olgadays.synology.me
    :enginebot_port: 9104