development:
  :saas_keyword_host: localhost
  :saas_keyword_port: 9251
  :saas_backlink_host: localhost
  :saas_backlink_port: 9252
test:
  :saas_keyword_host: 192.168.1.88
  :saas_keyword_port: 9251
  :saas_backlink_host: 192.168.1.88
  :saas_backlink_port: 9252
production:
  :saas_keyword_host: 192.168.1.88
  :saas_keyword_port: 9251
  :saas_backlink_host: 192.168.1.88
  :saas_backlink_port: 9252